name: C++ CI with CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSVC environment
      uses: microsoft/setup-msbuild@v1.1

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G "Visual Studio 17 2022"

    - name: Build project
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Run tests
      run: ${{github.workspace}}/build/Release/mcbe.exe